//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTiendaOnline_U2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle
    {
        public int id_detalle { get; set; }
        public int id_factura { get; set; }
        public int id_producto { get; set; }
        public int cantidad { get; set; }
        public decimal precio { get; set; }
        public decimal precioUnitario { get; set; }
        public decimal total { get; set; }
        public decimal IVA { get; set; }
    
        public virtual factura factura { get; set; }
        public virtual producto producto { get; set; }
    }
}
